miwi_clusters:
  hosts:
    miwi415:
      name: aro
      version: 4.15.35
    miwi414:
      name: aro
      version: 4.14.38
    miwi_private:
      name: aro
      apiserver_visibility: Private
      ingress_visibility: Private
    miwi_udr:
      name: aro
      version: 4.15.35
      apiserver_visibility: Private
      ingress_visibility: Private
      outbound_type: UserDefinedRouting
      HAS_INTERNET: false
      routes:
        - name: Blackhole
          address_prefix: 0.0.0.0/0
          next_hop_type: none
  vars:
    resource_group: "{{ CLUSTERPREFIX }}-{{ inventory_hostname }}-{{ location }}"
    network_prefix_cidr: 10.0.0.0/22
    master_cidr: 10.0.0.0/23
    master_vm_size: Standard_D8s_v3
    worker_cidr: 10.0.2.0/23
    worker_vm_size: Standard_D2s_v3
    AZAROEXT_VERSION: https://github.com/Azure/ARO-RP.git
    rp_mode: development
    mock_msi_object_id: 1e164816-35fb-43f3-b5b7-fdefdb30e0b8
    aro_api_version: 2024-08-12-preview
