---
standard_clusters:
  children:
    udr_clusters:

udr_clusters:
  # https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x
  hosts:
    udr41225:
      version: 4.12.25
    udr41260:
      version: 4.12.60
    udr413:
      version: 4.13.40
    udr414:
      version: 4.14.38
    udr415:
      version: 4.15.35
    udr416:
      version: 4.16.30
      create_csp: true
  vars:
    name: aro
    resource_group: "{{ CLUSTERPREFIX }}-{{ inventory_hostname }}-{{ location }}"
    HAS_INTERNET: false
    network_prefix_cidr: 10.0.0.0/22
    master_cidr: 10.0.0.0/23
    worker_cidr: 10.0.2.0/23
    apiserver_visibility: Private
    ingress_visibility: Private
    outbound_type: UserDefinedRouting
    dns_servers:
      # Break DNS with an impossible address, because the default 168.63.129.16 is always reachable
      # https://learn.microsoft.com/en-us/azure/openshift/howto-custom-dns
      - 172.16.0.0
    domain: "{{ inventory_hostname }}.{{ location }}.private"
    routes:
      - name: Blackhole
        address_prefix: 0.0.0.0/0
        next_hop_type: none
