---
standard_clusters:
  # "standard" in the sense that the unspecialized standard_cluster role will work
  # See byok_cluster for an example that is not "standard"
  hosts:
    basic:
      # The simplest possible cluster
      name: aro
      version: 4.16.30
    enc:
      # Basic cluster with encryption-at-host enabled
      name: aro-414
      version: 4.16.30
      master_vm_size: Standard_E8s_v5
      master_encryption_at_host: true
      worker_vm_size: Standard_D4s_v5
      worker_encryption_at_host: true
  vars:
    resource_group: "{{ CLUSTERPREFIX }}-{{ inventory_hostname }}-{{ location }}"
    network_prefix_cidr: 10.0.0.0/22
    master_cidr: 10.0.0.0/23
    master_vm_size: Standard_D8s_v3
    worker_cidr: 10.0.2.0/23
    worker_vm_size: Standard_D4s_v3
  children:
    encrypted_clusters:
    private_clusters:
    udr_clusters:

byok_clusters:
  # Cluster with customer-managed disk encryption key
  # https://learn.microsoft.com/en-us/azure/openshift/howto-byok
  hosts:
    byok:
      name: aro
      version: 4.16.30
  vars:
    resource_group: "{{ CLUSTERPREFIX }}-{{ inventory_hostname }}-{{ location }}"
    network_prefix_cidr: 10.0.0.0/22
    master_cidr: 10.0.0.0/23
    master_vm_size: Standard_E8s_v5
    worker_cidr: 10.0.2.0/23
    worker_vm_size: Standard_D4s_v5

private_clusters:
  hosts:
    private:
      # Simple private cluster, no UDR
      name: aro
      version: 4.16.30
  vars:
    resource_group: "{{ CLUSTERPREFIX }}-{{ inventory_hostname }}-{{ location }}"
    apiserver_visibility: Private
    ingress_visibility: Private
    network_prefix_cidr: 10.0.0.0/22
    master_cidr: 10.0.0.0/23
    master_vm_size: Standard_D8s_v3
    worker_cidr: 10.0.2.0/23
    worker_vm_size: Standard_D4s_v3


udr_clusters:
  # https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x
  hosts:
    udr:
      name: aro
      version: 4.16.30
      routes:
        - name: Blackhole
          address_prefix: 0.0.0.0/0
          next_hop_type: none
  vars:
    HAS_INTERNET: false
    resource_group: "{{ CLUSTERPREFIX }}-{{ inventory_hostname }}-{{ location }}"
    network_prefix_cidr: 10.0.0.0/22
    master_cidr: 10.0.0.0/23
    worker_cidr: 10.0.2.0/23
    apiserver_visibility: Private
    ingress_visibility: Private
    outbound_type: UserDefinedRouting
    # Need to break DNS, because Azure DNS is reachable even with a blackhole default route
    dns_servers:
      - 172.16.0.0
