---
all:
  vars:
    upgrade_paths:
      fast_416: &upgrade_fast_416
        # https://access.redhat.com/labs/ocpupgradegraph/update_path?channel=stable-4.16&arch=x86_64&is_show_hot_fix=false&current_ocp_version=4.15.0&target_ocp_version=4.16.33
        - from: "4.15"
          channel: stable-4.16
          version: 4.16.33
          admin_acks:
            - { "data": { "ack-4.15-kube-1.29-api-removals-in-4.16": "true" } }
      fast_417: &upgrade_fast_417
        # https://access.redhat.com/labs/ocpupgradegraph/update_path?channel=fast-4.16&arch=x86_64&is_show_hot_fix=false&current_ocp_version=4.15.0&target_ocp_version=4.17.15
        - from: "4.15"
          channel: stable-4.16
          version: 4.16.33
          admin_acks:
            - { "data": { "ack-4.15-kube-1.29-api-removals-in-4.16": "true" } }
        - from: "4.16"
          channel: stable-4.17
          version: 4.17.15
          #admin_acks:
          # No admin-acks identified at https://docs.openshift.com/container-platform/4.17/updating/preparing_for_updates/updating-cluster-prepare.html
      fast_418: &upgrade_fast_418
        # https://access.redhat.com/labs/ocpupgradegraph/update_path?channel=fast-4.18&arch=x86_64&is_show_hot_fix=false&current_ocp_version=4.16.0&target_ocp_version=4.18.3
        # channel: fast-4.18
        # path: 4.16.0 - 4.16.33 - 4.17.15 - 4.18.3
        - from: "4.15"
          channel: stable-4.16
          version: 4.16.33
          admin_acks:
            - { "data": { "ack-4.15-kube-1.29-api-removals-in-4.16": "true" } }
        - from: "4.16"
          channel: stable-4.17
          version: 4.17.15
          #admin_acks:
          # No admin-acks identified at https://docs.openshift.com/container-platform/4.17/updating/preparing_for_updates/updating-cluster-prepare.html
        - from: "4.17"
          channel: fast-4.18
          version: 4.18.3
          #admin_acks:
          # No admin-acks identified at https://docs.openshift.com/container-platform/4.18/updating/preparing_for_updates/updating-cluster-prepare.html

standard_clusters:
  # "standard" in the sense that the unspecialized standard_cluster role will work
  # See byok_cluster for an example that is not "standard"
  hosts:
    basic-416:
      upgrade: *upgrade_fast_416
    basic-417:
      upgrade: *upgrade_fast_417
    basic-418:
      upgrade: *upgrade_fast_418
  vars:
    name: aro
    resource_group: "{{ CLUSTERPREFIX }}-{{ inventory_hostname }}-{{ location }}"
    version: 4.16.30
    network_prefix_cidr: 10.0.0.0/22
    master_cidr: 10.0.0.0/23
    master_vm_size: Standard_D8s_v3
    worker_cidr: 10.0.2.0/23
    worker_vm_size: Standard_D4s_v3
  children:
    baddns_clusters:
    encrypted_clusters:
    udr_clusters:

udr_clusters:
  # https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x
  hosts:
    udr-416:
      upgrade: *upgrade_fast_416
    udr-417:
      upgrade: *upgrade_fast_417
    udr-418:
      upgrade: *upgrade_fast_418
  vars:
    name: aro
    resource_group: "{{ CLUSTERPREFIX }}-{{ inventory_hostname }}-{{ location }}"
    version: 4.16.30
    network_prefix_cidr: 10.0.0.0/22
    master_cidr: 10.0.0.0/23
    worker_cidr: 10.0.2.0/23
    apiserver_visibility: Private
    ingress_visibility: Private
    HAS_INTERNET: false
    outbound_type: UserDefinedRouting
    routes:
      - name: Blackhole
        address_prefix: 0.0.0.0/0
        next_hop_type: none
