- name: Create resource group
  ansible.builtin.include_tasks:
    file: ../../tasks/create_resourcegroup.yaml
- name: Create vnet and subnets
  ansible.builtin.include_tasks:
    file: ../../tasks/create_vnet.yaml
- name: Create MIWI identities
  ansible.builtin.include_tasks:
    file: create_identities.yaml
- name: Create aro cluster
  ansible.builtin.include_tasks:
    file: ../../tasks/create_aro_cluster.yaml
